### PR TITLE
fix joint names in controller parameters

### LINKED ISSUE #30: Bug: Docker launch sim
when running `roslaunch pai sim.launch` in the Docker the launch fail

```
[ERROR] [1686156460.241993689, 1.435000000]: Exception thrown while initializing controller 'right_front_ctrl'.
Could not find resource 'right_front_joint' in 'hardware_interface::VelocityJointInterface'.
```

I thought it might be related with missing ROS depedencies in however even after installing all the dependencies in https://github.com/cychitivav/pai/blob/951ca9c63c6fe73660dc87310d84bdb785153710/Dockerfile. The problem still persisted.

### PR DESCRIPTION
**Pull request by cychitivav**
Close #30

### CODE REVIEW

**Comment by cychitivav** [comment]
When I was fixing this bug, I found that we had other error with the velocity controller:

```bash
[ERROR] [1686320325.248472569, 0.485000000]: Could not load controller 'front_left_ctrl' because controller type 'velocity_controllers/JointVelocityController' does not exist.
[ERROR] [1686320325.248558463, 0.485000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
```

I run `rosservice call controller_manager/list_controller_types` and I got:

* types: 
  - diff_drive_controller/DiffDriveController
  - joint_state_controller/JointStateController
  - position_controllers/JointGroupPositionController
  - position_controllers/JointPositionController
* base_classes: 
  - controller_interface::ControllerBase
  - controller_interface::ControllerBase
  - controller_interface::ControllerBase
  - controller_interface::ControllerBase

Therefore, I was exploring this error and I realized that Dockerfile does not have enough ros-control dependencies

**Comment by jsduenass** [comment]
Hello @cychitivav 
These changes fix the error. thanks!
 
the sim launch no runs properly however there is still a error message when running the launch. 

```
[ INFO] [1686329777.086303155, 0.103000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ERROR] [1686329777.234286226, 0.103000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_right_joint
[ERROR] [1686329777.235855333, 0.103000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/back_right_joint
[ERROR] [1686329777.238360616, 0.103000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/front_left_joint
[ERROR] [1686329777.239884674, 0.103000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/back_left_joint

```

any thoughts on this?

**Comment by cychitivav** [comment]
> This error is because ros control needs at least a PID constant, but we have not tested the control part. Therefore, I am going to write a preliminar p constant in order to avoid this error.

**Edit**: I checked the gazebo ros documentation and it is an error that can be ignored because it is an error that gazebo generates when used with ros control and this does not generate problems in the simulation.

**Review by jsduenass — APPROVED** [review]
LGTM. Merging.

**Pull request merged**
